-- Dev-only demo placements (~$18,925 raised, 28 brands).
-- Generated by scripts/reseed-demo.ts against the 80x112 milestone world grid.
-- Do not hand-edit: rerun the script instead so coordinates stay milestone-legal.
DELETE FROM placements WHERE is_demo = true;

INSERT INTO placements (
  brand_name,
  website_url,
  creative_url,
  creative_fit,
  mime_type,
  x,
  y,
  width_cells,
  height_cells,
  amount_cents,
  status,
  requester_hash,
  reservation_expires_at,
  is_demo,
  paid_at
)
VALUES
  ('Launch Club', 'https://launchclub.ai/', '/placeholders/launch-club.webp', 'cover', 'image/webp', 36, 52, 8, 8, 160000, 'paid', 'demo-seed', now(), true, now()),
  ('Voximo', 'https://voximo.io/', '/placeholders/voximo.webp', 'cover', 'image/webp', 37, 60, 9, 5, 112500, 'paid', 'demo-seed', now(), true, now()),
  ('daily.fun', 'https://x.com/dailyfun', '/placeholders/daily-fun.webp', 'cover', 'image/webp', 39, 48, 10, 4, 100000, 'paid', 'demo-seed', now(), true, now()),
  ('Outdo', 'https://outdo.lol/', '/placeholders/outdo.webp', 'cover', 'image/webp', 40, 43, 8, 5, 100000, 'paid', 'demo-seed', now(), true, now()),
  ('Viktor', 'https://ref.viktor.com/1milllionpixels', '/placeholders/viktor.webp', 'cover', 'image/webp', 42, 65, 8, 4, 80000, 'paid', 'demo-seed', now(), true, now()),
  ('Zoom Into Art', 'https://zoominto.art/collections/phone-cases', '/placeholders/zoom-into-art.webp', 'cover', 'image/webp', 30, 50, 6, 6, 90000, 'paid', 'demo-seed', now(), true, now()),
  ('BuyerBuilds', 'https://buyerbuilds.com/', '/placeholders/buyerbuilds.webp', 'cover', 'image/webp', 34, 42, 6, 6, 90000, 'paid', 'demo-seed', now(), true, now()),
  ('MakePost AI', 'https://makepostai.com/', '/placeholders/makepost-ai.webp', 'cover', 'image/webp', 30, 65, 10, 3, 75000, 'paid', 'demo-seed', now(), true, now()),
  ('Replit', 'https://replit.com/', '/placeholders/replit.webp', 'cover', 'image/webp', 32, 68, 10, 2, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('Metrician', 'https://www.metrician.io/?utm_source=1millionpixels', '/placeholders/metrician.webp', 'cover', 'image/webp', 30, 48, 9, 2, 45000, 'paid', 'demo-seed', now(), true, now()),
  ('Rolevate', 'https://rolevate.com/en', '/placeholders/rolevate.webp', 'cover', 'image/webp', 30, 60, 7, 2, 35000, 'paid', 'demo-seed', now(), true, now()),
  ('Solbid', 'https://solbid.lol/', '/placeholders/solbid.webp', 'cover', 'image/webp', 30, 62, 7, 3, 52500, 'paid', 'demo-seed', now(), true, now()),
  ('GoldRock AI', 'https://utk.ai/', '/placeholders/goldrock-ai.webp', 'cover', 'image/webp', 44, 55, 6, 2, 30000, 'paid', 'demo-seed', now(), true, now()),
  ('Auctra', 'https://sellonauctra.com/', '/placeholders/auctra.webp', 'cover', 'image/webp', 44, 57, 9, 3, 67500, 'paid', 'demo-seed', now(), true, now()),
  ('ATC.com', 'https://www.atc.com/', '/placeholders/atc.webp', 'cover', 'image/webp', 34, 39, 9, 3, 67500, 'paid', 'demo-seed', now(), true, now()),
  ('Agent Outbid', 'https://agentoutbid.com/', '/placeholders/agent-outbid.webp', 'cover', 'image/webp', 32, 70, 9, 3, 67500, 'paid', 'demo-seed', now(), true, now()),
  ('DingDong', 'https://www.dingdong.so/?utm_source=1millionpixels', '/placeholders/dingdong.webp', 'cover', 'image/webp', 43, 40, 9, 3, 67500, 'paid', 'demo-seed', now(), true, now()),
  ('GigaFaze', 'https://gigafaze.com/', '/placeholders/gigafaze.webp', 'cover', 'image/webp', 32, 73, 9, 3, 67500, 'paid', 'demo-seed', now(), true, now()),
  ('Freyja', 'https://freyja.software/', '/placeholders/freyja.webp', 'cover', 'image/webp', 27, 71, 5, 5, 62500, 'paid', 'demo-seed', now(), true, now()),
  ('Bazarak', 'https://www.bazarak.me/', '/placeholders/bazarak.webp', 'cover', 'image/webp', 48, 60, 5, 5, 62500, 'paid', 'demo-seed', now(), true, now()),
  ('Adonis', 'https://www.meetadonis.ai/', '/placeholders/adonis.webp', 'cover', 'image/webp', 47, 35, 5, 5, 62500, 'paid', 'demo-seed', now(), true, now()),
  ('Ranla', 'https://ranla.ai/', '/placeholders/ranla.webp', 'cover', 'image/webp', 29, 44, 5, 4, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('Ignite Images', 'https://ignite-images.co.uk/ai-photo-booth/', '/placeholders/ignite-images.webp', 'cover', 'image/webp', 27, 41, 7, 3, 52500, 'paid', 'demo-seed', now(), true, now()),
  ('Still Lit', 'https://stilllit.live/', '/placeholders/still-lit.webp', 'cover', 'image/webp', 26, 61, 4, 6, 60000, 'paid', 'demo-seed', now(), true, now()),
  ('Digital Finest', 'https://www.digitalfinest.com/', '/placeholders/digital-finest.webp', 'cover', 'image/webp', 44, 69, 6, 3, 45000, 'paid', 'demo-seed', now(), true, now()),
  ('BlueAlpha', 'https://bluealpha.ai/', '/placeholders/bluealpha.webp', 'cover', 'image/webp', 41, 72, 10, 2, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('The Lobby', 'https://www.thelobbynews.com/', '/placeholders/the-lobby.webp', 'cover', 'image/webp', 25, 56, 10, 2, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('React Bits Pro', 'https://pro.reactbits.dev/', '/placeholders/react-bits-pro.webp', 'cover', 'image/webp', 25, 52, 4, 4, 40000, 'paid', 'demo-seed', now(), true, now());
