-- Dev-only demo placements (~$17,600 raised, 20 brands).
-- Generated by scripts/reseed-demo.ts against the 80x112 milestone world grid.
-- Do not hand-edit: rerun the script instead so coordinates stay milestone-legal.
DELETE FROM placements WHERE is_demo = true;

INSERT INTO placements (
  brand_name,
  website_url,
  creative_url,
  creative_fit,
  mime_type,
  x,
  y,
  width_cells,
  height_cells,
  amount_cents,
  status,
  requester_hash,
  reservation_expires_at,
  is_demo,
  paid_at
)
VALUES
  ('Amazon', 'https://amazon.com', '/logos/amazon.svg', 'contain', 'image/svg+xml', 32, 53, 16, 6, 240000, 'paid', 'demo-seed', now(), true, now()),
  ('Apple', 'https://apple.com', '/logos/apple.svg', 'contain', 'image/svg+xml', 36, 45, 8, 8, 160000, 'paid', 'demo-seed', now(), true, now()),
  ('Airbnb', 'https://airbnb.com', '/logos/airbnb.svg', 'contain', 'image/svg+xml', 36, 59, 8, 7, 140000, 'paid', 'demo-seed', now(), true, now()),
  ('Netflix', 'https://netflix.com', '/logos/netflix.svg', 'contain', 'image/svg+xml', 30, 47, 6, 6, 90000, 'paid', 'demo-seed', now(), true, now()),
  ('YouTube', 'https://youtube.com', '/logos/youtube.svg', 'contain', 'image/svg+xml', 44, 48, 6, 5, 75000, 'paid', 'demo-seed', now(), true, now()),
  ('Shopify', 'https://shopify.com', '/logos/shopify.svg', 'contain', 'image/svg+xml', 31, 59, 5, 6, 75000, 'paid', 'demo-seed', now(), true, now()),
  ('Slack', 'https://slack.com', '/logos/slack.svg', 'contain', 'image/svg+xml', 44, 59, 5, 5, 62500, 'paid', 'demo-seed', now(), true, now()),
  ('Dropbox', 'https://dropbox.com', '/logos/dropbox.svg', 'contain', 'image/svg+xml', 44, 44, 5, 4, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('Stripe', 'https://stripe.com', '/logos/stripe.svg', 'contain', 'image/svg+xml', 44, 64, 4, 4, 40000, 'paid', 'demo-seed', now(), true, now()),
  ('Figma', 'https://figma.com', '/logos/figma.svg', 'contain', 'image/svg+xml', 41, 66, 3, 4, 30000, 'paid', 'demo-seed', now(), true, now()),
  ('Webflow', 'https://webflow.com', '/logos/webflow.svg', 'contain', 'image/svg+xml', 37, 66, 4, 4, 40000, 'paid', 'demo-seed', now(), true, now()),
  ('Notion', 'https://notion.so', '/logos/notion.svg', 'contain', 'image/svg+xml', 36, 39, 8, 6, 120000, 'paid', 'demo-seed', now(), true, now()),
  ('Vercel', 'https://vercel.com', '/logos/vercel.svg', 'contain', 'image/svg+xml', 29, 40, 7, 7, 122500, 'paid', 'demo-seed', now(), true, now()),
  ('Linear', 'https://linear.app', '/logos/linear.svg', 'contain', 'image/svg+xml', 44, 38, 7, 6, 105000, 'paid', 'demo-seed', now(), true, now()),
  ('Spotify', 'https://spotify.com', '/logos/spotify.svg', 'contain', 'image/svg+xml', 26, 53, 6, 6, 90000, 'paid', 'demo-seed', now(), true, now()),
  ('GitHub', 'https://github.com', '/logos/github.svg', 'contain', 'image/svg+xml', 25, 59, 6, 6, 90000, 'paid', 'demo-seed', now(), true, now()),
  ('OpenAI', 'https://openai.com', '/logos/openai.svg', 'contain', 'image/svg+xml', 25, 47, 5, 6, 75000, 'paid', 'demo-seed', now(), true, now()),
  ('Adobe', 'https://adobe.com', '/logos/adobe.svg', 'contain', 'image/svg+xml', 48, 53, 4, 6, 60000, 'paid', 'demo-seed', now(), true, now()),
  ('Adidas', 'https://adidas.com', '/logos/adidas.svg', 'contain', 'image/svg+xml', 49, 59, 4, 5, 50000, 'paid', 'demo-seed', now(), true, now()),
  ('Nike', 'https://nike.com', '/logos/nike.svg', 'contain', 'image/svg+xml', 48, 64, 6, 3, 45000, 'paid', 'demo-seed', now(), true, now());
